server:
  port: 7060

spring:
  application:
    name: ruoyi-monitor
  boot:
    admin:
      notify:
        mail:
          to: chengyan0079@126.com
          from: 304338940@qq.com
      client:
        enabled: true
        url: http://172.27.0.7:7060
  mail:
    port: 465
    host: smtp.qq.com
    username: 304338940@qq.com
    password: ktugntqhbcrlbjaa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 1000
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 172.27.0.7:8848
#        server-addr: 139.155.70.19:8848
#      config:
#        enabled: false
    sentinel:
      log:
        dir: /home/chengy/logs/monitor/
      transport:
        dashboard: 172.27.0.7:8844
  security:
    user:
      name: "admin"
      password: "123456"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com

logging:
  config: classpath:logback-spring.xml