server:
  port: 7060

spring:
  application:
    name: ruoyi-monitor
  boot:
    admin:
      client:
        url: http://139.155.2.139:7060
      notify:
        mail:
          to: chengyan0079@126.com
          from: 304338940@qq.com
  mail:
    host: smtp.qq.com
    username: 304338940@qq.com
    password: mrjmwxnliadebjie
    smtp:
      auth: true
      starttls:
        enable: true
        required: true
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 139.155.2.139:8848
#      config:
#        enabled: false
    sentinel:
      log:
        dir: /home/chengy/logs/monitor/
      transport:
        dashboard: 139.155.2.139:8844

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com

logging:
  config: classpath:logback-spring.xml