server: 
  port: 9527

spring: 
  application:
    name: ruoyi-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        # ip: 182.148.123.6
        ip: 139.155.2.139
        enabled: true
        register-enabled: true
        server-addr: 139.155.70.19:8848
#      config:
#        enabled: false
    sentinel:
      log:
        dir: /home/chengy/logs/gateway/
      transport:
        dashboard: 139.155.70.19:8844
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/cyauth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        # user
        - id: ruoyi-user
          uri: lb://ruoyi-user
          predicates:
            - Path=/cyuser/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # activiti
        - id: ruoyi-activiti
          uri: lb://ruoyi-activiti
          predicates:
            - Path=/cyact/**
          filters:
            - StripPrefix=1
        # 代码生成
        - id: ruoyi-gen
          uri: lb://ruoyi-gen
          predicates:
          - Path=/cygen/**
          filters:
          - StripPrefix=1
        # provider
        - id: ruoyi-demo-provider
          uri: lb://ruoyi-demo-provider
          predicates:
          - Path=/cy pro/**
          filters:
          - StripPrefix=1
        # consumer
        - id: ruoyi-demo-consumer
          uri: lb://ruoyi-demo-consumer
          predicates:
          - Path=/cycon/**
          filters:
          - StripPrefix=1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  metrics:
    tags: # 通用标签
      application: ${spring.application.name}

logging:
  config: classpath:logback-spring.xml

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com

