server: 
  port: 9527
 
spring: 
  application:
    name: ruoyi-gateway
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:7060
      notify:
        mail:
          to: chengyan0079@126.com
          from: 304338940@qq.com
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: localhost:8848
#        server-addr: 192.168.0.101:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/cyauth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        # user
        - id: ruoyi-user
          uri: lb://ruoyi-user
          predicates:
            - Path=/cyuser/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # activiti
        - id: ruoyi-activiti
          uri: lb://ruoyi-activiti
          predicates:
            - Path=/cyact/**
          filters:
            - StripPrefix=1
        # 代码生成
        - id: ruoyi-gen
          uri: lb://ruoyi-gen
          predicates:
          - Path=/cygen/**
          filters:
          - StripPrefix=1
        # product
        - id: ruoyi-product
          uri: lb://ruoyi-product
          predicates:
          - Path=/cyprod/**
          filters:
          - StripPrefix=1
        # order
        - id: ruoyi-order
          uri: lb://ruoyi-order
          predicates:
          - Path=/cyorder/**
          filters:
          - StripPrefix=1
        # stock
        - id: ruoyi-stock
          uri: lb://ruoyi-stock
          predicates:
          - Path=/cystock/**
          filters:
          - StripPrefix=1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com

