server:
  port: 8131

dubbo:
  scan:
    base-packages: com.cy.ruoyi.search.service.impl
  protocol:
    name: dubbo
    # dubbo协议端口（-1表示自增，从20880开始）
    port: -1
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
  provider:
    timeout: 10000
    filter: -exception
    ESRestHighLevelApiService:
      version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

feign:
  #开启GZIP压缩
  compression:
    request:
      enable: true
      mime-types: text/xml,application/xml,application.json
      min-request-size: 2048 #通讯传输超过此大小便会进行压缩,减少通信性能损耗
    response:
      enable: true
  #feign对hystrix的支持
  hystrix:
    enabled: true

hystrix:
  command:
    default: #feign的service指定的服务
      execution:
        timeout:
          enabled: true
        isolation:
          thread.timeoutInMilliseconds: 5000 #一次请求服务的可用时间,若经常出错便会断路保护

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com

