spring:
  datasource:
    url: jdbc:mysql://139.155.70.19:3306/cy-ruoyi-soul?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&failOverReadOnly=false&autoReconnect=true
    username: root
    password: cy123456*
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
