spring:
  datasource:
    url: jdbc:mysql://cdb-35na54ha.cd.tencentcdb.com:10060/cy-ruoyi-soul?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true&useSSL=false
    username: root
    password: cy123456*
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver