server:
  port: 9095

spring:
  profiles:
    active: dev
  application:
    name: ruoyi-soul-admin
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  main:
    allow-bean-definition-overriding: true

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.cy.ruoyi.soul.admin.entity
  mapper-locations: classpath:/mappers/*.xml

soul:
  sync:
    strategy: websocket
#    zookeeper:
#      url: localhost:2181
#      sessionTimeout: 5000
#      connectionTimeout: 2000

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.springframework.boot: info
    org.dromara.soul: debug
    org:
      mybatis: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  metrics:
    tags: # 通用标签
      application: ${spring.application.name}

## 服务信息
#info:
#  name: @project.name@
#  version: @project.version@
#  description: @project.description@
#  author: chengyan
#  mail: 304338940@qq.com