server:
  port: 9527

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  metrics:
    tags: # 通用标签
      application: ${spring.application.name}


logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.dromara.soul.bonuspoint: info
    org.dromara.soul.lottery: info
    org.dromara.soul: info

# 服务信息
info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  author: chengyan
  mail: 304338940@qq.com
