server:
  port: 8051

#Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cy.ruoyi.stock
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #    key-mapper: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #    sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true


dubbo:
  scan:
    base-packages: com.cy.ruoyi.stock.impl.service
  protocol:
    name: dubbo
    # dubbo协议端口（-1表示自增，从20880开始）
    port: -1
  registry:
    address: spring-cloud://localhost
#    address: spring-cloud://192.168.31.138
  application:
    qos-enable: false
#  cloud:
##    subscribed-services: ruoyi-user
#  consumer:
#    timeout: 10000
#    check: false
#    filter: -exception
#    ISysUserService:
#      version: 1.0.0
  provider:
    timeout: 10000
    filter: -exception


feign:
  #开启GZIP压缩
  compression:
    request:
      enable: true
      mime-types: text/xml,application/xml,application.json
      min-request-size: 2048 #通讯传输超过此大小便会进行压缩,减少通信性能损耗
    response:
      enable: true
  #feign对hystrix的支持
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml
  level:
    com.cy.ruoyi.stock.api.feign: debug
    org:
      mybatis: debug

#对某一路由单独进行熔断配置如下,若统一所有服务熔断配置,将下面的服务名mobaopay-schrodinger改为default
hystrix:
  command:
    default: #feign的service指定的服务
      execution:
        timeout:
          enabled: true
        isolation:
          thread.timeoutInMilliseconds: 5000 #一次请求服务的可用时间,若经常出错便会断路保护